[package]
name = "opal"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[dependencies]
eframe = "0.32.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.9.2"
dirs = "6.0.0"
env_logger = "0.11.8"